safe: true
lsi: false
source: .
plugins:
  - jekyll-feed
feed:
  path: atom.xml
exclude:
  - CNAME
  - Dangerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - Rakefile
  - data_file_validator.rb
  - notes.txt
  - vendor
